Keyboards/KeyboardsBase/KeyboardViewController.swift
- PR for issue #168 
- Added required conjugation code references to [KeyboardsBase/KeyboardViewController.swift](https://github.com/scribe-org/Scribe-iOS/blob/main/Keyboards/KeyboardsBase/KeyboardViewController.swift) for all keyboard languages.
=> Fix: Returning conjugation to base conjugation for all keyboard languages

Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift, Keyboards/LanguageKeyboards/French/FRInterfaceVariables.swift, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Italian/ITInterfaceVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTInterfaceVariables.swift, Keyboards/LanguageKeyboards/Russian/RUInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift
- PR for first stage of issue #35 
- Added `translatePlaceholder`, `conjugatePlaceholder`, `pluralPlaceholder`, `translatePromptAndPlaceholder`, `conjugatePromptAndPlaceholder`, and `pluralPromptAndPlaceholder` to [CommandVariables.swift](https://github.com/scribe-org/Scribe-iOS/blob/47aa534852abeb76c28206a9030ddf2bacb616cd/Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift)
- Assigned corresponding values using Google Translate for all the keyboard languages in respective files.
@andrewtavis please review these changes. Thank you 😊
=> Assigning placeholder variables in all language keyboards

Keyboards/KeyboardsBase/Extensions.swift, Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandBar.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift, Keyboards/LanguageKeyboards/French/FRInterfaceVariables.swift, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Italian/ITInterfaceVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTInterfaceVariables.swift, Keyboards/LanguageKeyboards/Russian/RUInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift, Scribe.xcodeproj/project.pbxproj
- PR for the final stage of issue #35 
- Added a colorize function that returns an `NSMuttableAttributedString` to assign to the prompt in `CommandBar.swift`
- Made changes to all language keyboard interface variables to hold colored prompts that allow for checks during conditionally removing and adding the placeholder.
- Colorized prompt uses `commandBarBorderColorLight` or `commandBarBorderColorDark` depending on the appearance mode.
- Added an extension to `NSMuttableAttributedString` that allow us to color the required part of the prompt using a single function.
@andrewtavis please review these changes. This task was a big learning experience! Thanks! 😊
=> Feat: Adding colour to Placeholder prompts in Command Bar

Scribe/AppTexts/English/ENAppText.swift, Scribe/ViewController.swift
- PR for issue #178 
- Changed URL to direct to Scribe-iOS repository in files `ViewController.swift` and `ENAppText.swift` instead of the Scribe-org page.
@andrewtavis, please review these changes. Thank you :)
=> Fix: Changing Scribe-org link to Scribe-iOS repo link

Keyboards/KeyboardsBase/KeyboardStyling.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Scribe/AppTexts/AppTextStyling.swift
- PR for issue #165 
- Changed `arrow.turn.down.left` to` arrowTriangle.right.fill` in files [AppTextStyling.swift](https://github.com/scribe-org/Scribe-iOS/blob/bddbaaa1805d244f852ac46ec07eb47e4b253c0a/Scribe/AppTexts/AppTextStyling.swift) and [KeyboardViewController.swift](https://github.com/scribe-org/Scribe-iOS/blob/bddbaaa1805d244f852ac46ec07eb47e4b253c0a/Keyboards/KeyboardsBase/KeyboardViewController.swift)
- Added required symbol to [keysThatAreSlightlyLarger](https://github.com/scribe-org/Scribe-iOS/blob/bddbaaa1805d244f852ac46ec07eb47e4b253c0a/Keyboards/KeyboardsBase/KeyboardStyling.swift#L32) array to increase the size of the symbol relative to the other keys.
@andrewtavis, please review these changes at your convenience. Thank you so much 😊
=> UI: Changing return key symbol to arrowTriangle.right.fill

Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandBar.swift
Fixes #184 and has a few added parts. Included is:
- Adding some comments and docstrings to new functions added in #35, as well as formatting some comments that weren't written as complete sentences.
- Not sure if this is right, but I follow Python comment standards: comments that are their own line are sentences that should start with a capital letter and end with a period as they are complete sentences; inline comments don't need capitalization or periods.
- Renaming some variables and functions that I originally named very poorly and made the debug process way more tedious 🤦‍♂️
- Extracting `commandBar.textColor = keyCharColor` out of `CommandBar.setCornerRadiusAndShadow()`.
- Simplifying the implementation of `conditionallyRemovePlaceholder`:
- No need for `commandState == true` as it …
=> #184 fix placeholder deletion and add fxn docstrings

Keyboards/KeyboardsBase/ColorVariables.swift, Keyboards/KeyboardsBase/Keyboard.xib, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Annotate.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift
First part of #188 - I need to go to bed 😴😅
This PR includes everything that's ticked off in the issue. I'm generally referring to things as "auto actions", as we'd use the same functionality for autocomplete and autosuggest.
We now have autocomplete fields that lack functioning buttons. The fields are made by making the command bar the same color as the keyboard background, and then I added two little lines (`partitions`) to the .xib that show up when we're not in command mode or conjugating. When annotation of noun genders occurs, then the partition between fields 1 and 2 disappears if the word + annotation is long enough (I can explain this better). 
I'm having issues getting the buttons to effectively be clickable, and specifically we want to disable the first and maybe second …
=> #188 hackathon: add alphabetical autocomplete

Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift
- PR for second part issue #188 
- Added the required function that generate the next three words alphabetically for autocomplete.
- Set the buttons with the the appropriate text based on this array.
- This function takes into account only one word at a time. 
- That is when you enter a word and move to the next word in the sentence, it will suggest autocomplete only for that word.
- Also replaces the typed word with the auto completion instead of just adding it to the end of the user input.
@andrewtavis could you please review these changes! It was so nice to walk through the problem with you. No way was I otherwise figuring it out 😂
Thanks for the help!
=> Adding functions for autocomplete and assigning buttons

CHANGELOG.md, Keyboards/KeyboardsBase/Extensions.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift
- PR for part of issue #188 
- Fixed no capitalisation issue and added cases for CapsLock.
- Fixed autocomplete to work even when delete is pressed.
- This works by having a secondary variable called `secondaryPastStringOnDelete` that stores the previous version of the text in proxy. That way we can return the `pastStringInTextProxy` to the previous line.
@andrewtavis, could you please review these changes. Also could you look into the bug that crashes the keyboard when `delete` is pressed consecutively when the text proxy is empty? I mentioned the exact nature of it in the main issue comments.
=> Fixing gaps in autocomplete

CHANGELOG.md, Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/KeyboardsBase/KeyboardKeys.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Annotate.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandBar.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Conjugate.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Plural.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Translate.swift, Keyboards/LanguageKeyboards/French/FRInterfaceVariables.swift, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Italian/ITInterfaceVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTInterfaceVariables.swift, Keyboards/LanguageKeyboards/Russian/RUInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift
@SaurabhJamadagni, soooooooo here this is 😊
I hope this makes our lives much easier :) You'll see that there are more deletions than additions in this one 🚀 
There are lots of little changes in here:
- I renamed `isAlreadyPluralMessage` to `alreadyPluralMsg`, so disregard all those files
- Changes `commandState` to an `enum` as we discussed
- Updated the codes to work with the new version of it
- This included a ton of work in the main view controller
- I reordered lots of things so that we're accounting for all the variations of `commandState`
What this fixes:
- Hopefully the road ahead is a lot easier :)
- Fixes issues where the annotations were showing up on top of the invalid message (so translate something like `fdsjkal`, or use the plural command on something that already is plural) …
=> #188 refactoring incl commandState to enum

Keyboards/KeyboardsBase/Extensions.swift, Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift, Keyboards/LanguageKeyboards/French/FRInterfaceVariables.swift, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Italian/ITInterfaceVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTInterfaceVariables.swift, Keyboards/LanguageKeyboards/Russian/RUInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift
Alright, @SaurabhJamadagni, this is a lot more minor improvements to fix the bug where autocomplete wasn't being triggered after a command was used. I got carried away a bit again though 😊
What's included:
- The aforementioned bugfix
- Added an emum `AutoActionState` that determines if we're completing or suggesting
- I made a boolean at first and was like, "Waaaaaait a minute..... 😅"
- Fixed the sorting of the words for autocomplete so that it's done regardless of case
- Fixed the conditionals within autocomplete as we need to be able to type a lowercase word but get an uppercase/caps suggestion such as `germany -> Germany`
- Added variables for the first three words that appear whenever you load a system version of one of the Scribe languages that can serve as our default …
=> #188 #194 autocomplete bug fix and autosuggest placeholders

.github/ISSUE_TEMPLATE/data_wikidata.yml, Keyboards/KeyboardsBase/KeyboardViewController.swift
@SaurabhJamadagni, I think this is what we need to close #188 😊 I think that most of the problems were coming from `changePastTextsFromProxy`. The command prompt crash on delete was happening because we weren't checking to make sure that we weren't in a command within this function. Beyond this, I saw that the crash when the cursor is at the start of the proxy also stopped happening when I removed this function and it's call within `handleDeleteButtonPressed`. It seems that everything is working without this function, so could you just check all this and see if I'm removing it by accident? Autocomplete is updating as the user deletes, so maybe something in how the new `CommandState` enum is functioning fixed a bug that made this function not necessary anymore?
=> #188 fix to delete crash + minor template change

Keyboards/KeyboardsBase/KeyboardViewController.swift
- PR for issue #194 
- Adds body to `getAutosuggestions` function.
- Shifts suggestions a place to the left if annotations are active.
Hey @andrewtavis! Could you please review these changes. The function may look like it has repetitive code inside it but without it, it was not accepting input in different cases. For example, if the key "ich" was typed as "Ich", we could see that the key is present in the dictionary by comparing the lowercased strings. But what would happen is that when retrieving elements, "Ich" would be a wrong key as the correct key is "ich".
I think the two different cases I have considered work with all the permutations that are possible -- key lowercase and input uppercase OR key uppercase and input uppercase and so on. I hope that works. If you find a way I could …
=> Adding Autosuggestions function

CHANGELOG.md, Keyboards/KeyboardsBase/KeyboardStyling.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift
- adds method for styling delete button
- changes delete button's style when pressing similar to native delete button
- see video of the feature attached here: https://github.com/scribe-org/Scribe-iOS/issues/204#issuecomment-1260087859
=> Switch delete button when pressed

Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Conjugate.swift, Keyboards/LanguageKeyboards/French/FRCommandVariables.swift, Keyboards/LanguageKeyboards/German/DECommandVariables.swift, Keyboards/LanguageKeyboards/Italian/ITCommandVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTCommandVariables.swift, Keyboards/LanguageKeyboards/Russian/RUCommandVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESCommandVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVCommandVariables.swift
- PR for issue #211 
- Added an enum that holds the state for which button should be active.
- Assigned values to variable `conjViewShiftButtonsState` accordingly for all languages in their respective command variables file.
- Changed colour of chevron conditionally. I also used the `deactivate()` button method as otherwise it would still act as a button without performing any action.
@andrewtavis, could you please review these changes? 😊
=> Disable Conjugation View Shift buttons conditionally

Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift
- PR for issue #208 
- Added variables to hold pronouns to Present tense dictionary and also array for words that follow pronouns i.e. variations of [have, be, can].
- Created there corresponding instances in `DEInterfaceVariables`.
- Created a function that assigns the autosuggestions based on the values retrieved from the verbs dictionary.
@andrewtavis, I am hoping this is something close to what you intended. Let me know if you want me to make any changes. I created the `wordsAfterPronounsArray` so that it can be easier to add similar functionality for other languages later instead of hard coding the values directly in the function. 😊
=> Default autosuggestions after Pronouns in german

.github/ISSUE_TEMPLATE/new_keyboard.yml
What's in here:
- Adds a text form for information on keyboard variants in the `new_keyboard.yml` issue template
=> #229 docs: add variant info in new_keyboard issue

README.md
Here's my attempt at making them work, @SaurabhJamadagni 😊 I chose to just add them to the end of the top shields as we're just trying to prompt people when they land there to consider using them or sharing in their own way. I don't think that we need to put them on their own line :)
The twitter button has text with `#languagelearning` and the reddit button just has the URL and a general title, which I thought made sense as we're not sure where they'll post it. Your input is more than welcome!
=> #181 add Twitter and Reddit buttons to repo readme

Keyboards/KeyboardsBase/KeyboardViewController.swift
Added `currentPrefix.hasPrefix()` checks for `"`, `/`, `#`, and `(`. If the word begins with any of those punctuation, then `replaceOccurrences` will remove it in order to get the autocompletions. If we didn't wan't to call `currentPrefix.hasPrefix()` multiple times in the if statement, another workaround could be to store the initial character of the word as a constant and then check if the constant is `"`, `/`, `#`, or `(`. If you would rather do it that way or another way let me know and I can change it.
=> Fix: allow for autocomplete after certain punctuation -- ", /, #, (

CHANGELOG.md, Keyboards/KeyboardsBase/KeyboardViewController.swift
---
This pull request proposes to add support for highlighting the "AutoAction1" button given that the word being entered is the completion word at hand. The color of the button is changed to "keyColor" and given an alpha component to distinguish itself.
I tested that this change works by running Scribe in an emulator and typing the word listed in the "AutoAction1" button until they were a match. I then confirmed that the button was highlighted only when the word I had typed was the same as the word in the "AutoAction1" 
#250
=> Added support for highlight autocompletion

CHANGELOG.md, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift
---
- Adds insertion of autocompletion on spacebar.
- This works in the case if the user is mid-word and if there is only one possible autocompletion.
- In the case the user does not want the completion, the user entered word is offered as the first suggestion which can undo the insertion.
- Stores the previous word and if undo is allowed as boolean in separate variables.
- Files changed:
- KeyboardViewController.swift
- CommandVariables.swift
- PR for issue #256 
Hey @andrewtavis! Could you take a look at the changes? Sorry for the delay :)
=> feat: Adding space to insert autocompletion and undo

Keyboards/KeyboardsBase/KeyboardViewController.swift
---
This pull request modifies the KeyboardViewController.swift file to fix the bug of not showing suggestions after pressing the "Return Key". I have essentially set the commandState to idle and called conditionallySetAutoActionBtns() functions from CommandBar class to set the texts. 
The CommandBar works now and displays default auto suggestion texts after pressing return
Please review it and tell me if any changes are necessary. Thank you
#ISSUE_NUMBER
This PR fixes issue for #270
=> Add Autosuggestion texts to CommandBar after pressing Return

CHANGELOG.md, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/LanguageKeyboards/German/DECommandVariables.swift
---
Here demonstrative pronouns to German keyboard demo has been added. 
Manually tested all the available cases and it worked fine
#249
=> Add demostrativ pronouns

CHANGELOG.md, Keyboards/KeyboardsBase/KeyboardViewController.swift
---
Insert em dash when type double dash.
Tested on simulator iOS 16.2
- [#280](https://github.com/scribe-org/Scribe-iOS/issues/280)
=> Insert em dash when user does double dash

Keyboards/KeyboardsBase/KeyAltChars.swift, Keyboards/KeyboardsBase/KeyAnimation.swift, Keyboards/KeyboardsBase/KeyboardKeys.swift, Keyboards/KeyboardsBase/KeyboardStyling.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Conjugate.swift, Keyboards/LanguageKeyboards/French/FRCommandVariables.swift, Keyboards/LanguageKeyboards/German/DECommandVariables.swift, Keyboards/LanguageKeyboards/Italian/ITCommandVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTCommandVariables.swift, Keyboards/LanguageKeyboards/Russian/RUCommandVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESCommandVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVCommandVariables.swift, Scribe/ViewController.swift
=> fix: removed all explicit boolean comparisons

Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/LanguageKeyboards/French/French-AZERTY/FR-AZERTYInterfaceVariables.swift, Keyboards/LanguageKeyboards/French/French-QWERTY/FR-QWERTYInterfaceVariables.swift, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Italian/ITInterfaceVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTInterfaceVariables.swift, Keyboards/LanguageKeyboards/Russian/RUInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift
- [x ] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
---
- #33
=> Implemented and ignored number key row for ipad.

Keyboards/KeyboardsBase/KeyboardViewController.swift
---
Hey @andrewtavis, here are the changes for the part cursor move issue #291. I mostly just moved getting emoji suggestions from the getAutosuggestions function to a separate function of its own. That can be then called when the Scribe key is pressed. Sorry can't get this issue till the end. Not updating the CHANGELOG as the issue is still unresolved 😅 
- PR for issue #291
=> 291 cursor move updation

CHANGELOG.md, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Conjugate.swift, Keyboards/LanguageKeyboards/German/DECommandVariables.swift
Disclaimer: I have not contributed to open source before so I am not sure I did everything right.
First one is unchecked because I am not sure what it means. I could not find another branch besides 'main'.
---
Added German indefinite pronouns. Disabled the 'plural' button for the indefinite pronouns due to lack of an indefinite plural pronoun in German.
Tested by building the project and seeing that it worked (not sure how else I should check it)
- #303
=> Add indefinite pronouns

Keyboards/KeyboardsBase/ScribeFunctionality/Conjugate.swift
---
Moves cursor in between verb + prefix (for verbs with sep. prefixes) or verb + participle (for perf. ind.) after selecting word in conj. menu.
To this end, selecting a verb in perf. ind. now writes verb + part. instead of just part.
Tested manually.
- #155
=> Move cursor for separated verbs

Scribe.xcodeproj/project.pbxproj, Scribe/AboutTab/AboutTableData.swift, Scribe/AppExtensions.swift, Scribe/Components/ParentTableViewCell/ParentTableViewCell.swift, Scribe/InstallationTab/InstallationVC.swift, Scribe/ParentTableCellModel.swift, Scribe/SettingsTab/SettingsTableData.swift
---
PR adds interactivity to cells in the About section table view that redirect to a link or call for action.
- Section that redirect to a link are:
- GitHub, Matrix, Bug report
- Sections that call for action:
- Share Scribe, Rate Scribe, Email redirect
- #315
=> Adding social links and redirects to About section content

README.md
---
PR adds reference to blog post regarding GSoC documentation in `Featured By` section of the README.
- N/A
=> Adding reference to blog post 1 in README

Scribe/Base.lproj/AppScreen.storyboard, Scribe/Components/ParentTableViewCell/ParentTableViewCell.xib
---
Hey @andrewtavis!
Here's the PR for the design fixes that were discussed in our last meeting. I hope I have covered everything. Do let me know if I missed anything. The changes include:
- Increasing separation between sections as well as the first section and title.
- Changing tab bar icon colour to be `linkBlue` so that it is inverse of the current theme (dark or light mode).
- Increased the size of the settings icon a little.
N/A
=> Design fixes discussed in scribe weekly 3/7/23

French.entitlements, German.entitlements, Italian.entitlements, Keyboards/KeyboardsBase/KeyboardViewController.swift, Portuguese.entitlements, Russian.entitlements, Scribe.xcodeproj/project.pbxproj, Scribe/AboutTab/AboutTableData.swift, Scribe/AppDelegate.swift, Scribe/AppExtensions.swift, Scribe/Base.lproj/AppScreen.storyboard, Scribe/Components/InfoChildTableViewCell/CustomChildTableView.swift, Scribe/Components/InfoChildTableViewCell/InfoChildTableViewCell.swift, Scribe/Components/InfoChildTableViewCell/InfoChildTableViewCell.xib, Scribe/Components/ParentTableViewCell/ParentTableViewCell.swift, Scribe/Components/TableViewTemplateViewController.swift, Scribe/ParentTableCellModel.swift, Scribe/Scribe.entitlements, Scribe/SettingsTab/SettingsTableData.swift, Scribe/SettingsTab/SettingsViewController.swift, Spanish.entitlements, Swedish.entitlements
---
Hey @andrewtavis, here's one more giant PR again unfortunately 🙈 
The PR adds:
- Lists the installed keyboards
- Displays menu option to toggle between comma and period for keyboards
- Translates the preferences to the keyboard view controller on launching a particular language keyboard.
Regarding the problem I was facing about refreshing the list, it has been worked out in a very hacky manner for the moment. I will explain the problem better in the meeting tomorrow. The gist is that it works when we open the app on some other menu tab and then navigate to the `Settings` tab. This allows me to call the `viewWillAppear` method which takes care of the refresh. The refresh uses the Notification system. Publishes a notification whenever the value changes which is then handled by a …
=> Adding a Comma and Period option to the settings menu

Scribe/Components/InfoChildTableViewCell/InfoChildTableViewCell.swift, Scribe/ParentTableCellModel.swift, Scribe/SettingsTab/SettingsTableData.swift
---
Hey @andrewtavis, here's my attempt at trying to keep the PRs atomic and issue specific. 😅 
Will move on to the functionality implementation for emoji autosuggest menu item next. This PR adds:
- Menu option for toggling emoji autosuggestions
- Fixes toggle colours
Hope this works! Thanks 😄 
- #310
=> Emoji autosuggest menu

Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift
- [#33 ] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
---
- #33 
Added expanded DE keyboard settings
=> DE Keyboard Merge 

CONTRIBUTING.md, Keyboards/KeyboardsBase/KeyboardViewController.swift, README.md, Scribe/Components/InfoChildTableViewCell/InfoChildTableViewCell.swift
---
Following up on issue #310, this PR adds the functionality for emoji autosuggest menu item. Changes include:
- Adding the required reference in the userDefaults
- Function to check if enabled in KeyboardViewController
- #311 
Hey @andrewtavis, I tested this with most of the cases where emojis would be suggested. Seems to work so far. Let me know if you come across a case where the emojis are showing despite the menu item. Probably missing a condition in that case but currently I think all cases should be covered.
=> feat: saving user preference on emoji autosuggest based on menu

Keyboards/LanguageKeyboards/French/FRInterfaceVariables.swift, Keyboards/LanguageKeyboards/Italian/ITInterfaceVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTInterfaceVariables.swift, Keyboards/LanguageKeyboards/Russian/RUInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift
---
Add keyboards for French, Italian, Portuguese, Russian, Spanish, Swedish for the expanded version of the iPad and the symbols for those keyboards. 
- #33
=> Keyboards Update

Scribe.xcodeproj/project.pbxproj, Scribe/Base.lproj/AppScreen.storyboard
---
This PR adds the ability to swipe between menu tabs. It uses the [SwipeableTabBarController](https://github.com/marcosgriselli/SwipeableTabBarController) package. 
@andrewtavis could you test it out on a physical device if possible? Seems to work great on the simulator. I would have but then for me to run it on my device it will have to go and provision certificates for all languages and that's causing some problem.
- #337
=> Swiping between tabs using SwipeableTabBarController

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/data_wikidata.yml, .github/ISSUE_TEMPLATE/design_improvement.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/localization.yml, .github/ISSUE_TEMPLATE/new_keyboard.yml, .github/ISSUE_TEMPLATE/question.yml, .github/workflows/pr_maintainer_checklist.yaml
---
A quick PR for automatically adding new issues to the scribe board project. Done by editing the .yml files for issue templates and including the project in them.
- #355
=> Automatically add new issues to Scribe-Board - Scribe-iOS repo

Scribe/Info.plist, Scribe/InstallationTab/InstallationVC.swift
---
This PR sets light text in light mode in the Settings and About screens. Changes are:
- Info.plist:
- Set `UIStatusBarStyle` to *UIStatusBarStyleLightContent*. This sets the light text in the status bar for the entire app.
- Set `UIViewControllerBasedStatusBarAppearance` to *NO*. This prevents the status bar appearance to change within a screen.
- InstallationVC.swift: remove the override of the var `preferredStatusBarStyle`
- #353
=> Set light text in light mode in Settings and About screens

Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/LanguageKeyboards/English/ENInterfaceVariables.swift, Keyboards/LanguageKeyboards/French/FR-AZERTYInterfaceVariables.swift, Keyboards/LanguageKeyboards/French/FR-QWERTYInterfaceVariables.swift, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Italian/ITInterfaceVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTInterfaceVariables.swift, Keyboards/LanguageKeyboards/Russian/RUInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift
Made some changes - I am not completely done - but this is a first draft.
---
- #352
=> My first commit

Keyboards/LanguageKeyboards/English/ENInterfaceVariables.swift, Keyboards/LanguageKeyboards/French/FR-AZERTYInterfaceVariables.swift, Keyboards/LanguageKeyboards/French/FR-QWERTYInterfaceVariables.swift, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Italian/ITInterfaceVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTInterfaceVariables.swift, Keyboards/LanguageKeyboards/Russian/RUInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift
---
- As shown in the related issue, the current version of Scribe-iOS appends an extra delete key within each languages interface, specifically for IPad. The solution proposed in this PR removes said append in each interface.
- Testing for this change was done on an emulator for IPad and IPad Mini using Xcode.
- #366
=> Removing multiple delete keys on IPad

Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift, Scribe/Components/InfoChildTableViewCell/InfoChildTableViewCell.swift, Scribe/ParentTableCellModel.swift, Scribe/SettingsTab/SettingsTableData.swift
---
- Adding a toggle to the layout settings to disable accents from Spanish, Swedish, and German keyboards.
- Testing for this change was done on the XCode simulator for iPhone 15 Pro
- #339
=> Menu item to disable accent characters on keyboard letter keys

Keyboards/InterfaceConstants.swift, Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/KeyboardsBase/KeyAnimation.swift, Keyboards/KeyboardsBase/KeyboardKeys.swift, Keyboards/KeyboardsBase/KeyboardStyling.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Annotate.swift, Keyboards/LanguageKeyboards/Danish/DAInterfaceVariables.swift, Keyboards/LanguageKeyboards/English/ENInterfaceVariables.swift, Keyboards/LanguageKeyboards/French/FR-AZERTYInterfaceVariables.swift, Keyboards/LanguageKeyboards/French/FR-QWERTYInterfaceVariables.swift, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Hebrew/HEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Italian/ITInterfaceVariables.swift, Keyboards/LanguageKeyboards/Norwegian/NBInterfaceVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTInterfaceVariables.swift, Keyboards/LanguageKeyboards/Russian/RUInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift, Scribe.xcodeproj/project.pbxproj
---
This PR implements #371 by adding functionality for the new expanded layout that was introduced by #352.
The `indent` key is now fully functional as well as the `capslock` key.
**Old design**
https://github.com/scribe-org/Scribe-iOS/assets/1595177/6a6765a9-b749-4554-a032-5fcba6e322dd
**New design**
https://github.com/scribe-org/Scribe-iOS/assets/1595177/4a0e4c1b-f187-4450-9976-7ad333543457
| Description | Screenshot |
|--------|--------|
| **New design (iPad)** | ![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-10-22 at 14 46 46](https://github.com/scribe-org/Scribe-iOS/assets/1595177/15fd622a-9106-4e93-bcf8-11465db63df3) |
| **Design on iPhone (no changes)** | ![Simulator Screenshot - iPhone 15 Pro - 2023-10-22 at 14 54 …
=> [#371] Add functionality for new keyboard expanded layout

CHANGELOG.md, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift, Scribe/Components/ParentTableViewCell/ParentTableViewCell.swift
=> Remove Disable accent characters for menus that it's not needed on #372

Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift
Removed some magic numbers and substituted them with constants. Issue: #379 
NOTE: There is more to be done here, but this is a first draft.
---
- #379
=> Refactoring keyboardviewcontroller #379

Keyboards/KeyboardsBase/KeyboardViewController.swift
---
I have made a simple refactoring of the code to replace while with for loop as suggested previously by @flumaves. 
In order to replace the logic for i+=1 due to the allowUndo if clause, I have used the continue keyword to skip to 0th indexed element in the event allowUndo evaluates to true. 
I have verified the new changes retain the same behaviour as previously.
I have also run the app in the simulator to ensure the keyboard view works as expected as shown in the attached screenshot.
- Fixes #380
Please let me know if there are any changes for me to make. Hoping to be able to submit my first contribution to this project!
=> Fixes #380: Code quality improvement by replacing while with for loop

Scribe/SettingsTab/SettingsViewController.swift
Added shadow to settings view
---
- #394
=> Added shadows to menu

CHANGELOG.md, Keyboards/KeyboardsBase/KeyboardViewController.swift
The pull request provides a solution for issue 396: noun-gender annotation formatting broken on device orientation change. In the app, annotation size and position is calculated depending on the frame of the assigned keys. I think the error occurs when auto layout changes the frames. To fix the bug, I called loadKeys() again when auto layout is finished.
The fix is tested on 
- iPhone 12, iOS 17.3.1. (physical device)
- iPhone 15, iOS 17.0. (simulator)
- iPhone 15 Pro, iOS 17.0. (simulator)
- iPad (10th generation), iOS 17.0 (simulator)
- iPhone SE (3rd generation), iOS 17.0 (simulator)
- #396
=> fix noun-gender annotation formatting on device orientation change #396

ScribeTemplates/ScribeHeader.xctemplate/TemplateInfo.plist, ScribeTemplates/ScribeHeader.xctemplate/___FILEBASENAME___.swift
---
This adds a template to a new directory called `ScribeTemplates`, which adds the copyright notice used in #403 to any newly created file using said template. You would find it when creating a new file in Xcode, where you would scroll to the bottom and select the template in a new category called "ScribeTemplates".
To use this template, you would first have to add it to your own Xcode templates by:
1. Creating a "Templates" directory in your Xcode folder (found at `Users/[your username]/Library/Developer/Xcode`)
2. Symlink the Scribe template into "Templates"
Using commands:
```
mkdir ~/Library/Developer/Xcode/Templates
ln -s [Path to your Scribe directory]/Scribe-iOS/ScribeTemplates ~/Library/Developer/Xcode/Templates/
```
- #405
=> File Template with Copyright Header

CHANGELOG.md, Keyboards/KeyboardsBase/KeyboardViewController.swift
---
The pull request provided by henrikth93 and Taufi offers a solution for issue #361: enabling swiping between conjugation and declension views. Alongside the existing left and right buttons used for view switching, users can now also swipe to navigate between views.
The fix is tested by henrikth93 and Taufi on
iPhone 12, iOS 17.3.1. (physical device)
iPhone 15, iOS 17.4. (simulator)
iPhone 15 Pro, iOS 17.0. (simulator)
iPad (10th generation), iOS 17.0 (simulator)
iPhone SE (3rd generation), iOS 17.0 (simulator)
Please note: Swipe gestures do not work with all simulators. It probably depends on whether XCode is running under Rosetta or not (https://forums.developer.apple.com/forums/thread/696832)
- #361
=> Allow for swiping between conjugation and declension views #361

Keyboards/KeyboardsBase/LanguageDBManager.swift, Scribe/ParentTableCellModel.swift
---
The UILexicon is unable to load due to the Language Database being located in the app's main bundle, where writing data is not permitted. The solution involves copying the database into the application support directory and accessing it from there.
Additionally, the pull request includes a minor fix for an issue in ParentTableCellModel.
The fix is tested on
- iPhone 12, iOS 17.3.1. (physical device)
- iPhone 15, iOS 17.0. (simulator)
- iPad (10th generation), iOS 17.0 (simulator)
- iPhone SE (3rd generation), iOS 17.0 (simulator)
The simulator tests are essentially retests because the error doesn't manifest there.
- #292
=> #292 Load UI lexicon

.swiftlint.yml, Scribe/AboutTab/InformationScreenVC.swift, Scribe/Components/InfoChildTableViewCell/InfoChildTableViewCell.swift, Scribe/ParentTableCellModel.swift
---
Removed `trailing_whitespace` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fixed all errors for it in the codebase.
**The linter fix was tested running: `swiftlint --no-cache --config ~/com.raywenderlich.swiftlint.yml` and tested on:**
- iPhone 15 Pro Max, iOS 17.4. (simulator)
- #429
=> #429 removed trailing_whitespace from disabled rules in .swiftlint.yml

.github/workflows/pr_swiftlint.yaml
---
Took a quick glance out of curiosity, and thought it odd that no SwiftLint errors were showing up for the following PRs: 
- https://github.com/scribe-org/Scribe-iOS/pull/437
- https://github.com/scribe-org/Scribe-iOS/pull/439
Peeked at what the workflow configuration looked like and noticed the event type. We've run into this before actually in some other small project :smirk: (https://github.com/activist-org/activist/pull/490) 
- :fist_raised:
=> fix(ci): correct event type 'pull_request'

Keyboards/KeyboardsBase/Keyboard.xib, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandBar.swift, Keyboards/KeyboardsBase/ScribeFunctionality/ScribeKey.swift
=> Fabuloui os inconsistent command bar outline behavior 423 new

.swiftlint.yml, Scribe/AboutTab/InformationScreenVC.swift
---
Removed `trailing_whitespace` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fixed all errors for it in the codebase.
**The linter fix was tested running: `swiftlint --no-cache --config ~/com.raywenderlich.swiftlint.yml` and tested on:**
- iPhone 15 Pro Max, iOS 17.4. (simulator)
- #430
=> Removed vertical_whitespace from disabled rules in .swiftlint.yml

.swiftlint.yml, Keyboards/KeyboardsBase/KeyboardViewController.swift
---
Removed `void_function_in_ternary` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fixed all errors for it in the codebase.
**The linter fix was tested running: `swiftlint --no-cache --config ~/com.raywenderlich.swiftlint.yml` and tested on:**
- iPhone 15 Pro Max, iOS 17.4. (simulator)
- #431
=> Removed void_function_in_ternary from disabled rules in .swiftint.yml

.swiftlint.yml, Keyboards/KeyboardsBase/KeyAnimation.swift, Keyboards/KeyboardsBase/KeyboardKeys.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Conjugate.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Plural.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Translate.swift
---
Removed `opening_brace` as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fixed all errors for it in the codebase.
**The linter fix was tested running: `swiftlint --no-cache --config ~/com.raywenderlich.swiftlint.yml` and tested on:**
- iPhone 15 Pro Max, iOS 17.4. (simulator)
- #426
=> Removed opening_brace from disabled rules in .swiftlint.yml

.swiftlint.yml, Scribe/SettingsTab/SettingsViewController.swift
=> Fabuloui os fix swift lint warning closure parameter position 434 new

.github/workflows/pr_swiftlint.yaml, .swiftlint.yml
=> Swift lint fix empty enum arguments throughout codebase 432

Keyboards/KeyboardsBase/KeyboardStyling.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Conjugate.swift, Keyboards/KeyboardsBase/ToolTip/ToolTipView.swift
---
When a word is present in Wikidata, but doesn't have any data for conjugation, the buttons in the conjugation screen show "Not in Wikidata" in the specific keyboard's language instead.
Here I added a little info symbol to these buttons. Clicking them now leads the user to an info view describing how Scribe data is fetched from Wikidata, the same one used when entering a word missing from the database.
- #400
=> Added explanation for conjugations missing from Wikidata (#400)

.pre-commit-config.yaml, CHANGELOG.md, CONTRIBUTING.md, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ToolTip/Protocol/ToolTipViewDatasourceable.swift, Keyboards/KeyboardsBase/ToolTip/Protocol/ToolTipViewUpdatable.swift, Keyboards/KeyboardsBase/ToolTip/Protocol/ViewThemeable.swift, README.md
Created pre-commit-config.yaml and installed hooks.
---
- #450
=> Created .pre-commit-config.yaml and installed hooks

CHANGELOG.md, Scribe.xcodeproj/project.pbxproj, Scribe/Extensions/UIDeviceExtensions.swift, Scribe/InstallationTab/InstallationVC.swift
---
- #ISSUE_NUMBER
https://github.com/scribe-org/Scribe-iOS/issues/467
=> 467 standardize app hints implementation to assure consistent locations

Keyboards/KeyboardsBase/InterfaceVariables.swift, Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/LanguageDBManager.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandBar.swift, Keyboards/KeyboardsBase/ScribeFunctionality/CommandVariables.swift, Keyboards/KeyboardsBase/ToolTip/Model/ToolTipViewDatasource.swift, Keyboards/KeyboardsBase/ToolTip/ToolTipView.swift, Scribe/AboutTab/AboutViewController.swift, Scribe/AppDelegate.swift, Scribe/Colors/UIColor+ScribeColors.swift, Scribe/Components/InfoChildTableViewCell/InfoChildTableViewCell.swift, Scribe/Components/TableViewTemplateViewController.swift, Scribe/Components/UITableViewCells/AboutTableViewCell.swift, Scribe/Extensions/UIEdgeInsetsExtensions.swift, Scribe/InstallationTab/DownloadDataVC.swift, Scribe/InstallationTab/InstallationVC.swift, Scribe/SettingsTab/SettingsViewController.swift, Scribe/Views/BaseTableViewController.swift
---
Implemented a check for iPad to remove **Layout** section from langSpecific settings.
- #477
=> Remove accent characters menu option from i pads 477

CONTRIBUTING.md
---
Just an example of how the workflow might look like..
- Running the following in project root to pull in changes from Scribe-i18n:
`git subtree pull --prefix Scribe/i18n git@github.com:scribe-org/Scribe-i18n.git main --squash`
- Then two commits as seen here in this PR get auto-created 
I'll look into formalizing the documentation for this over the weekend. It'll likely be best to have a generic version in the Scribe-i18n repo, but then quick repo-specific ones for each project.
P.S. Cool to see, though, that the command still appears to work despite other updates having occurred without using the command. The diff here likely appears empty, since I'd guess the manual updates to the i18n folder still matched, which is a good sign.   
- :globe_with_meridians:
=> Subtree pull Scribe-i18n

.swiftlint.yml, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift
---
Removed orphaned_doc_comment as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fixed all errors for it in the codebase (there was only one violation).
After removing `orphaned_doc_comment` from `disabled_rules`, I fixed the only violation by removing an orphaned comment that was a duplicate of part of the file's header doc string. At that point, no SwiftLint warnings were shown, and running `swiftlint --strict` in the project root confirmed: `Done linting! Found 0 violations, 0 serious in 86 files.` This rule would now be enforced by SwiftLint to prevent further violations from entering the codebase.
Since only .swiftlint.yml and comments were changed, it would not affect any running code, however I verified on the iPhone …
=> Enable SwiftLint orphaned_doc_comment rule and fix violation

.swiftlint.yml, CHANGELOG.md, Keyboards/KeyboardsBase/KeyboardViewController.swift, Scribe/AboutTab/InformationScreenVC.swift, Scribe/InstallationTab/InstallationVC.swift, Scribe/SettingsTab/SettingsTableData.swift
---
Removed for_where as a disabled rule from [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and fixed all errors for it in the codebase.
After removing `for_where` from `disabled_rules`, I fixed all 6 violations by removing the if statement within each affected for-loop, and moving the condition into a `where` clause on the for-loop itself. This is the preferred syntax for SwiftLint enforced by the `for_where` rule, and this refactor does not affect functionality. After making those changes, no SwiftLint warnings were shown, and running `swiftlint --strict` in the project root confirmed: `Done linting! Found 0 violations, 0 serious in 86 files.` This rule would now be enforced by SwiftLint to prevent further violations from entering the codebase.
I …
=> refactor(swiftlint): enable for_where and fix violations

Keyboards/KeyboardsBase/KeyboardViewController.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Annotate.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Conjugate.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Plural.swift, Keyboards/KeyboardsBase/ScribeFunctionality/Translate.swift, Keyboards/KeyboardsBase/Utilities.swift, Scribe/InstallationTab/InstallationVC.swift
---
These are changes to the behaviour of the Scribe key when text in the text field is selected. Currently, it only shows you annotations for the selected word (i.e. "N" for neuter words). Here, I changed it so the selected Scribe command's action is executed on the highlighted text.
We also considered an option where the text would simply be entered into the command bar's text field, but decided against it:
- #141
=> Enter selected text into Scribe

.swiftlint.yml
There are no violations currently in the project. We can enable this rule moving forward to prevent future violations.
---
I removed `blanket_disable_command` from `disabled_rules` in [.swiftlint.yml](https://github.com/scribe-org/Scribe-iOS/blob/main/.swiftlint.yml) and no violations were flagged. 
Running `swiftlint --strict` confirmed: `Done linting! Found 0 violations, 0 serious in 86 files.` This rule can now be enforced by SwiftLint moving forward to prevent new violations from entering the codebase. 
The only change was removing this line from from .swiftlint.yml so no functionality is affected. App builds and runs as normal on iPhone 15 Pro simulator (iOS 17.5).
- #427
=> refactor(swiftlint): remove blanket_disable_command from disabled rules

Keyboards/KeyboardsBase/KeyboardViewController.swift, Scribe/Components/InfoChildTableViewCell/InfoChildTableViewCell.swift, Scribe/ParentTableCellModel.swift, Scribe/SettingsTab/SettingsTableData.swift, Scribe/i18n/Scribe-i18n/Localizable.xcstrings
---
Add an option in the Functionality section for each language keyboard, that allow user to turn off double space period shortcuts , turn on by default.
Reference Figma design [here](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=513-1616&t=NJXqQ7FTAzV8nwwy-4).
- #479
=> Add an option to toggle double space period shortcuts.

Keyboards/KeyboardBuilder.swift, Keyboards/KeyboardProvider.swift, Keyboards/LanguageKeyboards/Danish/DAInterfaceVariables.swift, Keyboards/LanguageKeyboards/English/ENInterfaceVariables.swift, Keyboards/LanguageKeyboards/French/FR-AZERTYInterfaceVariables.swift, Keyboards/LanguageKeyboards/German/DEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Hebrew/HEInterfaceVariables.swift, Keyboards/LanguageKeyboards/Italian/ITInterfaceVariables.swift, Keyboards/LanguageKeyboards/Norwegian/NBInterfaceVariables.swift, Keyboards/LanguageKeyboards/Portuguese/PTInterfaceVariables.swift, Keyboards/LanguageKeyboards/Russian/RUInterfaceVariables.swift, Keyboards/LanguageKeyboards/Spanish/ESInterfaceVariables.swift, Keyboards/LanguageKeyboards/Swedish/SVInterfaceVariables.swift, Scribe.xcodeproj/project.pbxproj
the iPhone keyboard could be replaced with difference currency symbols
---
In this task, modify the keyboard generation from static to dynamic using the builder pattern which allows the keyboard to replace currency symbols (also can replace other symbols).
* #238
=> Make the keyboard able to replace currency symbols

Scribe.xcodeproj/project.pbxproj, Tests/Keyboards/KeyboardsBase/TestKeyboardStyling.swift
---
Add a unit tests for [KeyboardStyling.swift](https://github.com/scribe-org/Scribe-iOS/blob/e3ed1de13585ac74f486d48cfad72c9a2a0b9675/Keyboards/KeyboardsBase/KeyboardStyling.swift).
- #8
=> Add unit tests for KeyboardStyling

Keyboards/LanguageKeyboards/Hebrew/HECommandVariables.swift
---
Completed the HE file from the EN version. Added all the translations for the needed terms.
- #134
=> Completed the HECommandVariables file

CHANGELOG.md, README.md, Scribe/AboutTab/AboutTableData.swift, Scribe/AppTexts/AppTextStyling.swift, Scribe/AppTexts/InstallScreen.swift, Scribe/Base.lproj/AppScreen.storyboard, Scribe/InstallationTab/InstallationVC.swift, Scribe/SettingsTab/SettingsViewController.swift, Scribe/Views/Cells/InfoChildTableViewCell/InfoChildTableViewCell.swift, Scribe/Views/Cells/UITableViewCells/AboutTableViewCell.swift, Scribe/i18n/.github/workflows/pr_maintainer_checklist.yaml, Scribe/i18n/Scribe-i18n/Localizable.xcstrings
---
The yellow corner on the installation screen now flips based on the orientation of the user's app language. The orientation for LTR languages stays the same.
- #513
=> Flip install screen corner for RTL languages

Scribe/Views/BaseTableViewController.swift
This pull request addresses an issue where letters were being clipped in section headers, especially in right-to-left (RTL) languages like Arabic.
[x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
[x] I have tested my code with the xcodebuild 
The following changes were made:
Adjusted padding for section headers to ensure proper layout and prevent clipping.
Applied consistent styling for both LTR and RTL layouts.
Tested using xcodebuild and verified compliance with swiftlint --strict.
These changes improve the visual appearance and usability of the app for all supported languages.
- #518
Print Screen:
=> Fix: Adjust header padding to prevent letter clipping in RTL layouts.

Scribe/AboutTab/AboutViewController.swift, Scribe/Base.lproj/AppScreen.storyboard, Scribe/InstallationTab/InstallationVC.swift, Scribe/SettingsTab/SettingsViewController.swift
---
Added logic to dynamically update the "Installation" tab bar item title when the language changes. The solution involved adding the following line to the InstallationViewController:
``` 
title = NSLocalizedString("app.installation.title", value: "Installation", comment: "")
```
I forgot to remove the following code from SettingsViewController, which can be safely removed without any issues:
```
@objc func setText() {
tabBarController?.tabBar.items?[0].title = NSLocalizedString("Installation", comment: "").uppercased()
}
override func viewWillDisappear(_ animated: Bool) {
super.viewWillDisappear(animated)
NotificationCenter.default.removeObserver(self)
}
```
These were added while I was working on solving the tab bar title issue, and they are no longer needed.
- #517
=> Fix: Update tab bar titles on language change

Keyboards/KeyboardsBase/KeyboardKeys.swift, Scribe/i18n/Scribe-i18n/Localizable.xcstrings
---
Switch from conditional statements to switch and case statements to determine the keyboard width.
``` swift
switch key {
case "ABC", "АБВ":
layer.setValue(true, forKey: "isSpecial")
widthAnchor.constraint(equalToConstant: numSymKeyWidth * 1).isActive = true
case "#+=", "selectKeyboard":
layer.setValue(true, forKey: "isSpecial")
widthAnchor.constraint(equalToConstant: numSymKeyWidth * scalarSpecialKeysWidth).isActive = true
case "delete":
layer.setValue(true, forKey: "isSpecial")
widthAnchor.constraint(equalToConstant: numSymKeyWidth * scalarDeleteKeyWidth).isActive = true
case SpecialKeys.capsLock:
layer.setValue(true, forKey: "isSpecial")
widthAnchor.constraint(equalToConstant: numSymKeyWidth * scalarCapsLockKeyWidth).isActive = true
case SpecialKeys.indent:
layer.setValue(true, …
```
=> Switch case from conditional statement to determine keyboard width

CHANGELOG.md, Keyboards/KeyboardsBase/KeyboardViewController.swift
---
Made the period key visible on all keyboards when opened by a browser search engine, regardless of layout settings. 
Tested for functionality on iPad (iOS 17.5) and iPhone (iOS 18.5) simulators using the following test cases. iPad functionality is not affected by this change.
- Browser search bar text input with "comma and period" option selected
- Browser search bar text input with "comma and period" option deselected
- Non-browser text input with "comma and period" option selected
- Non-browser text input with "comma and period" option deselected
- #447
=> Added period to keyboard for any browser input
